create table menu
(
    id bigint generated by default as identity,
    parent_id bigint,
    name varchar(255),
    list_order int,
    primary key(id),
    foreign key (parent_id) references menu(id)
)